title               : Arun Jayaramakrishnan
description         : >-                               # >- means to ignore newlines until "url:"
                      Hi I am a generalist who is passionate to build software products. Have held product roles in multiple entrepreneurial stints. 
                  Currently revamping <a href="swarajyamag.com">swarajyamag.com</a> 
                  and revamped mobile app is on <a href="https://play.google.com/store/apps/details?id=com.swarajyamag.mobile.android">playstore</a>
                  
                  Here is a <a href="templesofindia.org">temples wiki</a> made by me and my friend.
                
url                 : "https://vyshnav2255.github.io/Minimal-Portfolio-Website/"
repository          : Vyshnav2255/Minimal-Portfolio-Website 

email: example@xyz.xyz
github_user: Vyshnav2255
instagram: vyshnavgangadharan
twitter: ThisIsVyshnav
dribbble: vyshnav_


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock