title               : John Doe
description         : >-                               # >- means to ignore newlines until "url:"
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

url                 : "/" 

email: example@xyz.xyz
github_user: Vyshnav2255
instagram: vyshnavgangadharan
twitter: ThisIsVyshnav
dribbble: vyshnav_